f::
{
WinWait, Genshin Impact
WinWaitActive, Genshin Impact
send,{w down}
sleep,6
Click, 1675, 976, 1;??
sleep,10
Click, 1512, 666, 1;
sleep,10
Click, 1512, 780, 1;
sleep,6
Click, 1512, 735, 1;
sleep,6
send,{w up}
sleep,6
return
}
numpad1::
{
WinWait, Genshin Impact
WinWaitActive, Genshin Impact
send, {e up}
sleep,3
send, {e up}
sleep,3
send, {e up}
sleep,3
send, {e down}
sleep,196
Send,{LSHIFT}
sleep,1
Send,{LSHIFT}
sleep,1
send, {e down}
send, {e up}
send, {e down}
send, {e up}
send,3
send,3
sleep,1
send,3
sleep,1
send,3
send,3
send,3
send,3
sleep,1
send, {e up}
send, {e up}
send, {e up}
send, {e up}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
send, {e down}
sleep, 1500
Reload
sleep, 1500
Return
}


numpad3::
while(1){
Click, 1412, 666, 1;
Click, 1412, 666, 1;
sleep, 160
send,r
sleep,50
send,r
sleep,10
}
F10::
while(1){
WinWait, Genshin Impact
WinWaitActive, Genshin Impact
Click, 1512, 666, 1;
sleep,61
Click, 1512, 780, 1;
sleep,62
Click, 1512, 735, 1;
sleep,63
}
F12::Reload
sleep, 1000
